### ISSUE TITLE
Error in installation with php7.3 composer

### ISSUE THREAD

**Issue by ioannisgz** [scandipwa/slider#4]
Hi. We are trying to install ScandiPWA for an existing magento store with composer.
But we get this error:
scandipwa/slider 2.0.0 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0|~7.2.0 -> your PHP version (7.3.16) does not satisfy that requirement.
    - scandipwa/slider 1.0.1 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0|~7.2.0 -> your PHP version (7.3.16) does not satisfy that requirement.
    - scandipwa/slider 1.0.0 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0|~7.2.0 -> your PHP version (7.3.16) does not satisfy that requirement.

Isn't working with php7.3?

**Comment by alfredsgenkins** [comment]
https://github.com/scandipwa/slider/releases/tag/2.0.1 - fixes your issue. Please re-open if it fails on PHP7.3
